[package]
name = "hello_rocket"
version = "0.1.0"
authors = ["NaokiM03 <naoki.matsumura@sansan.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.5"
