version: "3"
services:
  app:
    image: rust:1.36
    container_name: sandbox_rs
    environment:
      TZ: 'Asia/Tokyo'
    working_dir: /rust
    # ports: 
    #   - "8000:8000"
    stdin_open: true
    tty: true
    volumes:
      - .:/rust
