version: "3"
services:
  app:
    image: rust:1.30
    container_name: rust-1.30
    environment:
      TZ: 'Asia/Tokyo'
    working_dir: /rust
    stdin_open: true
    tty: true
    volumes:
      - .:/rust
