[package]
name = "exercises"
version = "0.1.0"
authors = ["NaokiM03 <mattsun.phone@gmail.com>"]
edition = "2018"

[dependencies]
# pulldown-cmark
pulldown-cmark = "0.6.0"
# clap
clap = "2.33.0"
# reqwest
reqwest = "0.9.22"
env_logger = "0.7.1"
